package studio.mgn.command

/** Every user-facing string on the command screen; built by the app layer. */
data class CommandStrings(
    val rulerTitlePrefix: String,
    val level: String,
    val turn: String,
    val endTurn: String,
    val processing: String,
    val decisionsPending: String,
    val councilTitle: String,
    val councilOpen: String,
    val latestEvents: String,
    val indicatorsTitle: String,
    val missionsTitle: String,
    val showAll: String,
    val reportTitle: String,
    val reportClose: String,
    val reportTreasury: String,
    val reportNewEvents: String,
    val reportAchievements: String,
    val reportMissions: String,
    val decisionsTitle: String,
    val decisionsEmpty: String,
    val reroll: String,
    val gemsSuffix: String,
    val notEnoughGems: String,
    val chooseResult: String,
    val continueLabel: String,
    val buildNow: String,
    val rushLabel: String,
    val builtLabel: String,
    val underConstructionLabel: String,
    val lockedSoon: String,
    val placeholderSection: String,
    val relationLabel: String,
    val treatiesLabel: String,
    val noTreaties: String,
    val remainingTurns: String,
    val costLabel: String,
    val effectsPreview: String,
    /** Arabic label per state key / section / cell. */
    val keyLabels: Map<String, String>,
    val sectionLabels: Map<String, String>,
)
